### ISSUE TITLE
バランスボード版の同時押しノーツに関して

### ISSUE THREAD

**Issue by Na27i** [shirry0129/MusicGame#32]
同時押しノーツがわかりにくいので同時押しノーツの色を変更希望．小節毎のガイドラインもあるといいかも．

**Comment by shirry0129** [comment]
小節毎のガイドライン，maimaiは無いんすよ．だからとりあえず付けてなかったんだけど，あったほうがいいかね?

**Comment by Na27i** [comment]
あ，そうなのね．じゃあとりあえずノーツ色だけ実装って感じですかね．

**Comment by shirry0129** [comment]
そっすね．ノーツ用画像の色が固定になってしまってるのでそれがなんとかなれば．画像処理系も出来たはずなのでちょっと探してみる(いつになるかは不明

**Comment by shirry0129** [comment]
balanceBoard版での動作確認待ち．
